def happy_numbers(a, b, c, d, e, f, g, h, i, j):
    print(a)
    print(b)
    print(c)
    print(d)
    print(e)
    print(f)
    print(g)
    print(h)
    print(i)
    print(j)
    print(h, h, j, j, e, e, e, c, e, c, e)
happy_numbers(1, 2, 3, 4, 5, 6, 7, 8, 9, 0)